
--  Question No. 1
/*
1. Calculate the number of transactions for each payment type. 
2. Calculate the total revenue generated from each payment type. 
3. Using these two values, determine the average transaction value for each 
	payment type and rank them in descending order.
*/
--
SELECT
	p.paytid,
    p.paytype AS paymentType,
    COUNT(*) AS transaction_count,
    ROUND(SUM(t.final_amount)::numeric, 2) AS total_revenue,
    ROUND(AVG(t.final_amount)::numeric, 2) AS avg_transaction_value,
	DENSE_RANK() OVER (ORDER BY ROUND(AVG(t.final_amount)::numeric, 2) DESC) AS rnk
FROM transactions AS t
INNER JOIN payment_types AS p
    ON p.paytid = t.paymentid
GROUP BY p.paytid, p.paytype;

------------------------ ---------------------------------- --------------------------


-- Question No. 2
/*
1.	Calculate total transactions per city.
2.	Calculate total revenue per city.
3.	Compute average revenue per transaction and rank cities.

*/
--
WITH city_metrics AS (
SELECT
    c.city,
    COUNT(*) AS total_transactions,
    ROUND(SUM(t.final_amount)::numeric,2) AS total_revenue,
    ROUND(AVG(t.final_amount)::numeric,2) AS avg_revenue_per_transaction
FROM transactions t
JOIN customers c
ON t.custid = c.custid
GROUP BY c.city
)

SELECT *,
DENSE_RANK() OVER (
    ORDER BY avg_revenue_per_transaction DESC
) AS city_rank
FROM city_metrics;
------------------------ ---------------------------------- --------------------------




-- Question No. 3
/*
1.	Calculate total quantity sold per product.
2.	Calculate total revenue per product.
3.	Determine revenue per unit sold and rank products.

*/
--
WITH product_metrics AS (
SELECT 
    p.prodid,
    p.prodname,
    SUM(t.quantity) AS total_quantity,
    SUM(t.final_amount) AS total_revenue
FROM transactions t
JOIN products p
ON t.prodid = p.prodid
GROUP BY p.prodid, p.prodname
)

SELECT
    *,
    ROUND(total_revenue / NULLIF(total_quantity,0),2) AS revenue_per_unit,
    DENSE_RANK() OVER (
        ORDER BY total_revenue / NULLIF(total_quantity,0) DESC
    ) AS product_rank
FROM product_metrics
ORDER BY revenue_per_unit DESC;
------------------------ ---------------------------------- --------------------------



-- Question No. 4
/*
1.	Calculate total transactions per customer.
2.	Calculate total amount spent per customer.
3.	Return customers with more than 5 transactions and spending greater than 15000.
*/
--
WITH customer_metrics AS (
SELECT 
    c.custid,
    c.customer_name,
    COUNT(*) AS total_transactions,
    ROUND(SUM(t.final_amount)::numeric,2) AS total_spent
FROM transactions t
JOIN customers c
ON t.custid = c.custid
GROUP BY c.custid, c.customer_name
)

SELECT *
FROM customer_metrics
WHERE total_transactions > 5
AND total_spent > 15000;

------------------------ ---------------------------------- --------------------------



-- Question No. 5
/*
1.	Calculate number of distinct products purchased per customer.
2.	Calculate total transactions per customer.
3.	Return customers who purchased at least 5 distinct products.
*/
--
SELECT
    c.custid,
    c.customer_name,
    COUNT(DISTINCT t.prodid) AS distinct_products,
    COUNT(*) AS total_transactions
FROM transactions t
JOIN customers c
ON t.custid = c.custid
GROUP BY c.custid, c.customer_name
HAVING COUNT(DISTINCT t.prodid) >= 5;

------------------------ ---------------------------------- --------------------------



-- Question No. 6
/*
1.	Consider only transactions from the last 3 months.
2.	Calculate total transactions per customer.
3.	Calculate total spending per customer in that 3‑month window.
4.	Return customers who placed more than 2 transactions during this period.
*/
--
SELECT
    custid, 
    COUNT(*) AS transaction_count,
    ROUND(SUM(final_amount)::numeric,2) AS total_spent_last_3_months
FROM transactions
WHERE transaction_date <= DATE '2024-12-31' - INTERVAL '3 months'
GROUP BY custid
HAVING COUNT(*) > 2
ORDER BY transaction_count DESC;

------------------------ ---------------------------------- --------------------------



-- Question No. 7
/*
1.	Calculate total quantity sold per product category.
2.	Calculate total revenue per category.
3.	Determine revenue generated per unit sold for each category.
*/
--
SELECT
	p.prodCat, 
	SUM(t.quantity) AS total_quantity,
	SUM(t.final_amount) AS total_revenue,
	ROUND(SUM(t.final_amount)::numeric / NULLIF(SUM(t.quantity),0),2) AS revenue_per_unit
FROM transactions AS t
INNER JOIN products AS p
ON t.prodid = p.prodid
WHERE p.prodCat IN ('Food','Groceries')
GROUP BY p.prodCat;

------------------------ ---------------------------------- --------------------------



-- Question No. 8
/*
1.	Calculate total revenue generated by each product.
2.	Calculate number of distinct customers purchasing each product.
3.	Determine revenue per customer and rank products by this metric.
*/
--

SELECT
	prodid, 
	ROUND(SUM(final_amount)::numeric,2) AS total_revenue, 
	COUNT(DISTINCT custid) AS distinct_customers,
	ROUND((SUM(final_amount)::numeric/NULLIF(COUNT(DISTINCT custid),0)),2) AS revenue_per_customer
FROM transactions 
GROUP BY prodid
ORDER BY revenue_per_customer DESC;

------------------------ ---------------------------------- --------------------------



-- Question No. 9
/*
1.	Filter transactions that happened in the last 90 days.
2.	Calculate total transactions per payment type.
3.	Calculate total revenue generated by each payment type.
*/
--

SELECT
	p.paytype,
	COUNT(*) AS transaction_count,
	ROUND(SUM(t.final_amount)::numeric,2) AS total_revenue
FROM transactions AS t
INNER JOIN payment_types AS p
ON t.paymentid = p.paytid
WHERE transaction_date <= DATE '2024-12-31' - INTERVAL '3 Months'
GROUP BY p.paytype

------------------------ ---------------------------------- --------------------------



-- Question No. 10
/*
1.	Calculate total transactions per customer.
2.	Calculate number of distinct products purchased per customer.
3.	Identify customers with more than 3 transactions but only 1 distinct product.
*/
--

SELECT 
	custid,
	COUNT(final_amount) AS total_transactions,
	COUNT(DISTINCT prodid) AS distinct_products
FROM transactions
GROUP BY custid
ORDER BY total_transactions DESC;

------------------------ ---------------------------------- --------------------------



-- Question No. 11
/*
1.	Join customers, transactions, and products.
2.	Calculate revenue per city and category.
3.	Identify top category per city.
*/
--
WITH CTE AS (
SELECT 
	c.city, p.prodcat,
	ROUND(SUM(t.final_amount::numeric),2) AS total_revenue,
	RANK() OVER (PARTITION BY c.city ORDER BY SUM(t.final_amount::numeric) DESC) AS rnk
FROM transactions AS t
INNER JOIN customers AS c
ON t.custid = c.custid
INNER JOIN products AS p
ON t.prodid = p.prodid
GROUP BY c.city, p.prodcat )

SELECT city, prodcat, total_revenue
FROM CTE 
WHERE rnk = 1
ORDER BY total_revenue DESC;

------------------------ ---------------------------------- --------------------------

-- Question No. 12
/*
1.	Join customers, transactions, products.
2.	Calculate spending per customer per category.
3.	Identify top category per customer.
*/
--
WITH CTE AS (
SELECT c.customer_name, p.prodcat,
	ROUND(SUM(t.final_amount::numeric),2) AS total_spent,
	RANK() OVER (PARTITION BY c.customer_name ORDER BY SUM(t.final_amount::numeric) DESC) AS rnk
FROM transactions AS t
INNER JOIN customers AS c
ON t.custid = c.custid
INNER JOIN products AS p
ON t.prodid = p.prodid
GROUP BY c.customer_name, p.prodcat)

SELECT customer_name, prodcat, total_spent
FROM CTE 
WHERE rnk = 1
ORDER BY customer_name;



------------------------ ---------------------------------- --------------------------

-- Question No. 13
/*
1.	Join customers and transactions.
2.	Filter last 3 months.
3.	Calculate spending and return top customers.
*/
--
WITH CTE AS (
	SELECT 
		c.customer_name,
		SUM(t.final_amount::numeric) AS total_spent,
		RANK() OVER (ORDER BY SUM(t.final_amount::numeric) DESC) AS rnk 
	FROM transactions AS t
	INNER JOIN customers AS c
	ON t.custid = c.custid
	WHERE t.transaction_date <= DATE '2024-12-31' - INTERVAL '3 Months'
	GROUP BY c.customer_name)
	
SELECT customer_name, total_spent
FROM CTE 
WHERE rnk = 1



------------------------ ---------------------------------- --------------------------

-- Question No. 14
/*
1.	Join customers, transactions, payment_types.
2.	Compare preferred vs actual.
3.	Count matches.
*/
--
WITH CTE AS (
SELECT 
	c.preferredpaytype,
	t.paymentid,
	(CASE WHEN c.preferredpaytype = t.paymentid THEN 1 ELSE 0 END) AS identifier
FROM transactions AS t
INNER JOIN customers AS c
ON c.custid = t.custid
INNER JOIN payment_types AS p
ON p.paytid = t.paymentid)

SELECT
	COUNT(CASE WHEN identifier = 1 THEN 1 END) AS matchedCount
FROM CTE


------------------------ ---------------------------------- --------------------------

-- Question No. 15
/*
1.	Join customers, transactions, products.
2.	Count distinct cities per product.
3.	Return products in more than 1 city.
*/
--
SELECT 
	p.prodName,
	COUNT(DISTINCT c.city) AS distinct_cities
FROM transactions AS t
INNER JOIN customers AS c
ON c.custid = t.custid
INNER JOIN products AS p
ON p.prodid = t.prodid
GROUP BY p.prodName
HAVING COUNT(DISTINCT c.city) > 1



SELECT * FROM customers

------------------------ ---------------------------------- --------------------------

-- Question No. 16
/*
1.	Calculate total spending per customer.
2.	Rank customers based on total spending using a window function.
3.	Return top 3 customers based on rank.
*/
--
WITH CTE AS (
SELECT 
	c.customer_name, 
	SUM(t.final_amount) AS total_spent, 
	DENSE_RANK() OVER (ORDER BY SUM(t.final_amount) DESC) AS rnk 
FROM transactions AS t
INNER JOIN customers AS c
ON t.custid = c.custid
GROUP BY c.customer_name)

SELECT customer_name, total_spent, rnk 
FROM CTE
WHERE rnk <= 3;

------------------------ ---------------------------------- --------------------------

-- Question No. 17
/*
1.	Calculate total revenue per day.
2.	Use a window function to get previous day's revenue.
3.	Calculate day-over-day revenue change.
*/
--
WITH currentDayRevenue AS ( 
SELECT
	transaction_date,
	SUM(final_amount::numeric) AS curDAYR
FROM transactions
GROUP BY transaction_date)

SELECT transaction_date, curDAYR,
	COALESCE(LAG(curDAYR) OVER (ORDER BY transaction_date), 0) AS prevDAYR,
	(curDAYR::numeric - LAG(curDAYR) OVER (ORDER BY transaction_date)::numeric) AS change
FROM currentDayRevenue


------------------------ ---------------------------------- --------------------------

-- Question No. 18
/*
1.	Calculate total revenue per product.
2.	Partition by product category.
3.	Rank products within each category and return top product per category.
*/
--
WITH product_revenue AS (
SELECT
    p.prodname, p.prodcat,
    ROUND(SUM(t.final_amount)::numeric,2) AS total_revenue
FROM transactions t
JOIN products p
ON t.prodid = p.prodid
GROUP BY p.prodname, p.prodcat
),
calc AS (
SELECT prodname, prodcat, total_revenue,
	DENSE_RANK() OVER (PARTITION BY prodcat ORDER BY total_revenue DESC) AS rnk
FROM product_revenue
)
SELECT * FROM calc
WHERE rnk = 1;


------------------------ ---------------------------------- --------------------------

-- Question No. 19
/*
1.	Filter transactions in last 90 days.
2.	Calculate total spending per customer.
3.	Rank customers using window function.
4.	Return top 2 customers.
*/
--

WITH CTE AS (
	SELECT c.custid,
		ROUND(SUM(t.final_amount)::numeric,2) AS total_spent
	FROM transactions AS t
	INNER JOIN customers AS c
	ON t.custid = c.custid
	WHERE transaction_date <= DATE '2024-12-31' - INTERVAL '3 Months'
	GROUP BY c.custid
),
calc AS (
	SELECT custid, total_spent,
		DENSE_RANK() OVER (ORDER BY total_spent DESC) AS rnk
	FROM CTE
)
SELECT *
FROM calc
WHERE rnk <= 2;


------------------------ ---------------------------------- --------------------------

-- Question No. 20
/*
1.	Assign a row number to each transaction per customer ordered by date.
2.	Return transaction sequence for each customer.
*/
--





SELECT * FROM customers

------------------------ ---------------------------------- --------------------------